from pathlib import Path

RANDOM_SEED = 42

TRAIN_FRAC = 0.80
VAL_FRAC   = 0.10
# TEST_FRAC not set, it is implied, 1 - TRAIN_FRAC - VAL_FRAC

VAR_LABELS = {
    'SEQN': 'Respondent sequence number',
    'ALQ111': 'Ever had a drink of any kind of alcohol',
    'ALQ121': 'Past 12 mo how often have alcohol drink',
    'ALQ130': 'Avg # alcohol drinks/day - past 12 mos',
    'ALQ142': '# days have 4 or 5 drinks/past 12 mos',
    'ALQ270': '# times 4-5 drinks in 2 hrs/past 12 mos',
    'ALQ280': '# times 8+ drinks in 1 day/past 12 mos',
    'ALQ290': '# times 12+ drinks in 1 day/past 12 mos',
    'ALQ151': 'Ever have 4/5 or more drinks every day?',
    'ALQ170': 'Past 30 days # times 4-5 drinks on an oc',
    'BMDSTATS': 'Body Measures Component Status Code',
    'BMXWT': 'Weight (kg)',
    'BMIWT': 'Weight Comment',
    'BMXRECUM': 'Recumbent Length (cm)',
    'BMIRECUM': 'Recumbent Length Comment',
    'BMXHEAD': 'Head Circumference (cm)',
    'BMIHEAD': 'Head Circumference Comment',
    'BMXHT': 'Standing Height (cm)',
    'BMIHT': 'Standing Height Comment',
    'BMXBMI': 'Body Mass Index (kg/m**2)',
    'BMXLEG': 'Upper Leg Length (cm)',
    'BMILEG': 'Upper Leg Length Comment',
    'BMXARML': 'Upper Arm Length (cm)',
    'BMIARML': 'Upper Arm Length Comment',
    'BMXARMC': 'Arm Circumference (cm)',
    'BMIARMC': 'Arm Circumference Comment',
    'BMXWAIST': 'Waist Circumference (cm)',
    'BMIWAIST': 'Waist Circumference Comment',
    'BMXHIP': 'Hip Circumference (cm)',
    'BMIHIP': 'Hip Circumference Comment',
    'SDDSRVYR': 'Data release cycle',
    'RIDSTATR': 'Interview/Examination status',
    'RIAGENDR': 'Gender',
    'RIDAGEYR': 'Age in years at screening',
    'RIDAGEMN': 'Age in months at screening - 0 to 24 mos',
    'RIDRETH1': 'Race/Hispanic origin',
    'RIDRETH3': 'Race/Hispanic origin w/ NH Asian',
    'RIDEXMON': 'Six month time period',
    'RIDEXAGM': 'Age in months at exam - 0 to 19 years',
    'DMQMILIZ': 'Served active duty in US Armed Forces',
    'DMQADFC': 'Served in a foreign country',
    'DMDBORN4': 'Country of birth',
    'DMDCITZN': 'Citizenship status',
    'DMDYRSUS': 'Length of time in US',
    'DMDEDUC3': 'Education level - Children/Youth 6-19',
    'DMDEDUC2': 'Education level - Adults 20+',
    'DMDMARTL': 'Marital status',
    'RIDEXPRG': 'Pregnancy status at exam',
    'SIALANG': 'Language of SP Interview',
    'SIAPROXY': 'Proxy used in SP Interview?',
    'SIAINTRP': 'Interpreter used in SP Interview?',
    'FIALANG': 'Language of Family Interview',
    'FIAPROXY': 'Proxy used in Family Interview?',
    'FIAINTRP': 'Interpreter used in Family Interview?',
    'MIALANG': 'Language of MEC Interview',
    'MIAPROXY': 'Proxy used in MEC Interview?',
    'MIAINTRP': 'Interpreter used in MEC Interview?',
    'AIALANGA': 'Language of ACASI Interview',
    'DMDHHSIZ': 'Total number of people in the Household',
    'DMDFMSIZ': 'Total number of people in the Family',
    'DMDHHSZA': '# of children 5 years or younger in HH',
    'DMDHHSZB': '# of children 6-17 years old in HH',
    'DMDHHSZE': '# of adults 60 years or older in HH',
    'DMDHRGND': 'HH ref person\'s gender',
    'DMDHRAGZ': 'HH ref person\'s age in years',
    'DMDHREDZ': 'HH ref person\'s education level',
    'DMDHRMAZ': 'HH ref person\'s marital status',
    'DMDHSEDZ': 'HH ref person\'s spouse\'s education level',
    'WTINT2YR': 'Full sample 2 year interview weight',
    'WTMEC2YR': 'Full sample 2 year MEC exam weight',
    'SDMVPSU': 'Masked variance pseudo-PSU',
    'SDMVSTRA': 'Masked variance pseudo-stratum',
    'INDHHIN2': 'Annual household income',
    'INDFMIN2': 'Annual family income',
    'INDFMPIR': 'Ratio of family income to poverty',
    'DXAEXSTS': 'Exam Status',
    'DXAHEBV': 'Head Bone Invalidity Code',
    'DXXHEA': 'Head Area (cm^2)',
    'DXXHEBMC': 'Head Bone Mineral Content (g)',
    'DXXHEBMD': 'Head Bone Mineral Density (g/cm^2)',
    'DXAHETV': 'Head Tissue Invalidity Code',
    'DXXHEFAT': 'Head Fat (g)',
    'DXDHELE': 'Head Lean excl BMC (g)',
    'DXXHELI': 'Head Lean incl BMC (g)',
    'DXDHETOT': 'Head Total (g)',
    'DXDHEPF': 'Head Percent Fat',
    'DXALABV': 'Left Arm Bone Invalidity Code',
    'DXXLAA': 'Left Arm Area (cm^2)',
    'DXXLABMC': 'Left Arm BMC (g)',
    'DXXLABMD': 'Left Arm BMD (g/cm^2)',
    'DXALATV': 'Left Arm Tissue Invalidity Code',
    'DXXLAFAT': 'Left Arm Fat (g)',
    'DXDLALE': 'Left Arm Lean excl BMC (g)',
    'DXXLALI': 'Left Arm Lean incl BMC (g)',
    'DXDLATOT': 'Left Arm Total (g)',
    'DXDLAPF': 'Left Arm Percent Fat',
    'DXALLBV': 'Left Leg Bone Invalidity Code',
    'DXXLLA': 'Left Leg Area (cm^2)',
    'DXXLLBMC': 'Left Leg BMC (g)',
    'DXXLLBMD': 'Left Leg BMD (g/cm^2)',
    'DXALLTV': 'Left Leg Tissue Invalidity Code',
    'DXXLLFAT': 'Left Leg Fat (g)',
    'DXDLLLE': 'Left Leg Lean excl BMC (g)',
    'DXXLLLI': 'Left Leg Lean incl BMC (g)',
    'DXDLLTOT': 'Left Leg Total (g)',
    'DXDLLPF': 'Left Leg Percent Fat',
    'DXARABV': 'Right Arm Bone Invalidity Code',
    'DXXRAA': 'Right Arm Area (cm^2)',
    'DXXRABMC': 'Right Arm BMC (g)',
    'DXXRABMD': 'Right Arm BMD (g/cm^2)',
    'DXARATV': 'Right Arm Tissue Invalidity Code',
    'DXXRAFAT': 'Right Arm Fat (g)',
    'DXDRALE': 'Right Arm Lean excl BMC (g)',
    'DXXRALI': 'Right Arm Lean incl BMC (g)',
    'DXDRATOT': 'Right Arm Total (g)',
    'DXDRAPF': 'Right Arm Percent Fat',
    'DXARLBV': 'Right Leg Bone Invalidity Code',
    'DXXRLA': 'Right Leg Area (cm^2)',
    'DXXRLBMC': 'Right Leg BMC (g)',
    'DXXRLBMD': 'Right Leg BMD(g/cm^2)',
    'DXARLTV': 'Right Leg Tissue Invalidity Code',
    'DXXRLFAT': 'Right Leg Fat (g)',
    'DXDRLLE': 'Right Leg Lean excl BMC (g)',
    'DXXRLLI': 'Right Leg Lean incl BMC (g)',
    'DXDRLTOT': 'Right Leg Total (g)',
    'DXDRLPF': 'Right Leg Percent Fat',
    'DXXLRA': 'Left Ribs Area (cm^2)',
    'DXXLRBMC': 'Left Ribs BMC (g)',
    'DXXLRBMD': 'Left Ribs BMD (g/cm^2)',
    'DXXRRA': 'Right Ribs Area (cm^2)',
    'DXXRRBMC': 'Right Ribs BMC (g)',
    'DXXRRBMD': 'Right Ribs BMD (g/cm^2)',
    'DXXTSA': 'Thoracic Spine Area (cm^2)',
    'DXXTSBMC': 'Thoracic Spine BMC (g)',
    'DXXTSBMD': 'Thoracic Spine BMD (g/cm^2)',
    'DXXLSA': 'Lumbar Spine Area (cm^2)',
    'DXXLSBMC': 'Lumbar Spine BMC (g)',
    'DXXLSBMD': 'Lumbar Spine BMD (g/cm^2)',
    'DXXPEA': 'Pelvis Area (cm^2)',
    'DXXPEBMC': 'Pelvis BMC (g)',
    'DXXPEBMD': 'Pelvis BMD (g/cm^2)',
    'DXATRBV': 'Trunk Bone Invalidity Code',
    'DXDTRA': 'Trunk Bone area (cm^2)',
    'DXDTRBMC': 'Trunk BMC (g)',
    'DXDTRBMD': 'Trunk Bone BMD (g/cm^2)',
    'DXATRTV': 'Trunk Tissue Invalidity Code',
    'DXXTRFAT': 'Trunk Fat (g)',
    'DXDTRLE': 'Trunk Lean excl BMC (g)',
    'DXXTRLI': 'Trunk Lean incl BMC (g)',
    'DXDTRTOT': 'Trunk Total (g)',
    'DXDTRPF': 'Trunk Percent Fat',
    'DXDSTA': 'Subtotal Area (cm^2)',
    'DXDSTBMC': 'Subtotal BMC (g)',
    'DXDSTBMD': 'Subtotal BMD (g/cm^2)',
    'DXDSTFAT': 'Subtotal Fat (g)',
    'DXDSTLE': 'Subtotal Lean excl BMC (g)',
    'DXDSTLI': 'Subtotal Lean incl BMC (g)',
    'DXDSTTOT': 'Subtotal (Total excl Head) (g)',
    'DXDSTPF': 'Subtotal Percent Fat',
    'DXDTOA': 'Total Area (cm^2)',
    'DXDTOBMC': 'Total Bone Mineral Content (g)',
    'DXDTOBMD': 'Total Bone Mineral Density (g/cm^2)',
    'DXDTOFAT': 'Total Fat (g)',
    'DXDTOLE': 'Total Lean excl BMC (g)',
    'DXDTOLI': 'Total Lean incl BMC (g)',
    'DXDTOTOT': 'Total Lean+Fat (g)',
    'DXDTOPF': 'Total Percent Fat',
    'MCQ010': 'Ever been told you have asthma',
    'MCQ025': 'Age when first had asthma',
    'MCQ035': 'Still have asthma',
    'MCQ040': 'Had asthma attack in past year',
    'MCQ050': 'Emergency care visit for asthma/past yr',
    'AGQ030': 'Did SP have episode of hay fever/past yr',
    'MCQ053': 'Taking treatment for anemia/past 3 mos',
    'MCQ080': 'Doctor ever said you were overweight',
    'MCQ092': 'Ever receive blood transfusion',
    'MCD093': 'Year receive blood transfusion',
    'MCQ149': 'Menstrual periods started yet?',
    'MCQ151': 'Age in years at first menstrual period',
    'RHD018': 'Estimated age in months at menarche',
    'MCQ160A': 'Doctor ever said you had arthritis',
    'MCD180A': 'Age when told you had arthritis',
    'MCQ195': 'Which type of arthritis was it?',
    'MCQ160N': 'Doctor ever told you that you had gout?',
    'MCD180N': 'Age when told you had gout',
    'MCQ160B': 'Ever told had congestive heart failure',
    'MCD180B': 'Age when told you had heart failure',
    'MCQ160C': 'Ever told you had coronary heart disease',
    'MCD180C': 'Age when told had coronary heart disease',
    'MCQ160D': 'Ever told you had angina/angina pectoris',
    'MCD180D': 'Age when told you had angina pectoris',
    'MCQ160E': 'Ever told you had heart attack',
    'MCD180E': 'Age when told you had heart attack',
    'MCQ160F': 'Ever told you had a stroke',
    'MCD180F': 'Age when told you had a stroke',
    'MCQ160M': 'Ever told you had thyroid problem',
    'MCQ170M': 'Do you still have thyroid problem',
    'MCD180M': 'Age when told you had thyroid problem',
    'MCQ160G': 'Ever told you had emphysema',
    'MCD180G': 'Age when told you had emphysema',
    'MCQ160K': 'Ever told you had chronic bronchitis',
    'MCQ170K': 'Do you still have chronic bronchitis',
    'MCD180K': 'Age when told you had chronic bronchitis',
    'MCQ160O': 'Ever told you had COPD?',
    'MCQ160L': 'Ever told you had any liver condition',
    'MCQ170L': 'Do you still have a liver condition',
    'MCD180L': 'Age when told you had a liver condition',
    'MCQ500': 'Ever told you had any liver condition',
    'MCQ510A': 'Liver condition: Fatty liver',
    'MCQ510B': 'Liver condition: Liver fibrosis',
    'MCQ510C': 'Liver condition: Liver cirrhosis',
    'MCQ510D': 'Liver condition: Viral hepatitis',
    'MCQ510E': 'Liver condition: Autoimmune hepatitis',
    'MCQ510F': 'Liver condition: Other liver disease',
    'MCQ520': 'Abdominal pain during past 12 months?',
    'MCQ530': 'Where was the most uncomfortable pain',
    'MCQ540': 'Ever seen a DR about this pain',
    'MCQ550': 'Has DR ever said you have gallstones',
    'MCQ560': 'Ever had gallbladder surgery?',
    'MCQ570': 'Age when 1st had gallbladder surgery?',
    'MCQ203': 'Ever been told you have jaundice?',
    'MCQ206': 'Age when told you have jaundice?',
    'MCQ220': 'Ever told you had cancer or malignancy',
    'MCQ230A': '1st cancer - what kind was it?',
    'MCD240A': 'Age 1st cancer (MCQ230a) diagnosed',
    'MCQ230B': '2nd cancer - what kind was it?',
    'MCD240B': 'Age 2nd cancer (MCQ230b) diagnosed',
    'MCQ230C': '3rd cancer - what kind was it?',
    'MCD240C': 'Age 3rd cancer (MCQ230c) diagnosed',
    'MCQ230D': 'More than 3 kinds of cancer',
    'MCQ300B': 'Close relative had asthma?',
    'MCQ300C': 'Close relative had diabetes?',
    'MCQ300A': 'Close relative had heart attack?',
    'MCQ366A': 'Doctor told you to control/lose weight',
    'MCQ366B': 'Doctor told you to exercise',
    'MCQ366C': 'Doctor told you to reduce salt in diet',
    'MCQ366D': 'Doctor told you to reduce fat/calories',
    'MCQ371A': 'Are you now controlling or losing weight',
    'MCQ371B': 'Are you now increasing exercise',
    'MCQ371C': 'Are you now reducing salt in diet',
    'MCQ371D': 'Are you now reducing fat in diet',
    'OSQ230': 'Any metal objects inside your body?',
    'OSQ010A': 'Broken or fractured a hip',
    'OSQ010B': 'Broken or fractured a wrist',
    'OSQ010C': 'Broken or fractured spine',
    'OSQ020A': '# Times broken/fractured hip',
    'OSQ020B': '# Times broken/fractured wrist',
    'OSQ020C': '# Times broken/fractured spine',
    'OSD030AA': 'Age when fractured hip 1st time',
    'OSQ040AA': 'Under/over 50 when fracd. hip 1st time',
    'OSD050AA': 'Reason hip fracture occurred 1st time',
    'OSD030AB': 'Age when fractured hip 2nd time',
    'OSQ040AB': 'Under/over 50 when fracd. hip 2nd time',
    'OSD050AB': 'Reason hip fracture occurred 2nd time',
    'OSD030AC': 'Age when fractured hip 3rd time',
    'OSQ040AC': 'Under/over 50 when fracd. hip 3rd time',
    'OSD050AC': 'Reason hip fracture occurred 3rd time',
    'OSD030BA': 'Age when fractured wrist 1st time',
    'OSQ040BA': 'Under/over 50 when fracd. wrist 1st time',
    'OSD050BA': 'Reason wrist fracture occurred 1st time',
    'OSD030BB': 'Age when fractured wrist 2nd time',
    'OSQ040BB': 'Under/over 50 when fracd. wrist 2nd time',
    'OSD050BB': 'Reason wrist fracture occurred 2nd time',
    'OSD030BC': 'Age when fractured wrist 3rd time',
    'OSQ040BC': 'Under/over 50 when fracd. wrist 3rd time',
    'OSD050BC': 'Reason wrist fracture occurred 3rd time',
    'OSD030BD': 'Age when fractured wrist 4th time',
    'OSQ040BD': 'Under/over 50 when fracd. wrist 4th time',
    'OSD050BD': 'Reason wrist fracture occurred 4th time',
    'OSD030BE': 'Age when fractured wrist 5th time',
    'OSQ040BE': 'Under/over 50 when fracd. wrist 5th time',
    'OSD050BE': 'Reason wrist fracture occurred 5th time',
    'OSD030CA': 'Age when fractured spine 1st time',
    'OSQ040CA': 'Under/over 50 when fracd. spine 1st time',
    'OSD050CA': 'Reason spine fracture occurred 1st time',
    'OSD030CB': 'Age when fractured spine 2nd time',
    'OSQ040CB': 'Under/over 50 when fracd. spine 2nd time',
    'OSD050CB': 'Reason spine fracture occurred 2nd time',
    'OSD030CC': 'Age when fractured spine 3rd time',
    'OSQ040CC': 'Under/over 50 when fracd. spine 3rd time',
    'OSD050CC': 'Reason spine fracture occurred 3rd time',
    'OSD030CD': 'Age when fractured spine 4th time',
    'OSQ040CD': 'Under/over 50 when fracd. spine 4th time',
    'OSD050CD': 'Reason spine fracture occurred 4th time',
    'OSD030CE': 'Age when fractured spine 5th time',
    'OSQ040CE': 'Under/over 50 when fracd. spine 5th time',
    'OSD050CE': 'Reason spine fracture occurred 5th time',
    'OSQ080': 'Doctor ever told any other fractures?',
    'OSQ090A': 'Fracture result of severe trauma?',
    'OSQ100A': 'Where fracture occurred',
    'OSD110A': 'How old when fracture occurred?',
    'OSQ120A': 'Any other fractures?',
    'OSQ090B': 'Fracture result of severe trauma?',
    'OSQ100B': 'Where fracture occurred',
    'OSD110B': 'How old when fracture occurred?',
    'OSQ120B': 'Any other fractures?',
    'OSQ090C': 'Fracture result of severe trauma?',
    'OSQ100C': 'Where fracture occurred',
    'OSD110C': 'How old when fracture occurred?',
    'OSQ120C': 'Any other fractures?',
    'OSQ090D': 'Fracture result of severe trauma?',
    'OSQ100D': 'Where fracture occurred',
    'OSD110D': 'How old when fracture occurred?',
    'OSQ120D': 'Any other fractures?',
    'OSQ090E': 'Fracture result of severe trauma?',
    'OSQ100E': 'Where fracture occurred',
    'OSD110E': 'How old when fracture occurred?',
    'OSQ120E': 'Any other fractures?',
    'OSQ090F': 'Fracture result of severe trauma?',
    'OSQ100F': 'Where fracture occurred',
    'OSD110F': 'How old when fracture occurred?',
    'OSQ120F': 'Any other fractures?',
    'OSQ090G': 'Fracture result of severe trauma?',
    'OSQ120G': 'Any other fractures?',
    'OSQ090H': 'Fracture result of severe trauma?',
    'OSQ120H': 'Any other fractures?',
    'OSQ090I': 'Fracture result of severe trauma?',
    'OSQ120I': 'Any other fractures?',
    'OSQ090J': 'Fracture result of severe trauma?',
    'OSQ100J': 'Where fracture occurred',
    'OSD110J': 'How old when fracture occurred?',
    'OSQ120J': 'Any other fractures?',
    'OSQ060': 'Ever told had osteoporosis/brittle bones',
    'OSQ072': 'Doctor prescribe RX for osteoporosis?',
    'OSQ130': 'Ever taken prednisone or cortisone daily',
    'OSQ140Q': 'How long used prednisone or cortisone?',
    'OSQ140U': 'How long used prednisone or cortisone?',
    'OSQ150': 'Parents ever told had osteoporosis?',
    'OSQ160A': 'Mother was told had osteoporosis',
    'OSQ160B': 'Father was told had osteoporosis',
    'OSQ170': 'Did mother ever fracture hip?',
    'OSQ180': 'How old mother when fractured hip?',
    'OSQ190': 'Over or under 50 years old?',
    'OSQ200': 'Did father ever fracture hip?',
    'OSQ210': 'How old father when fractured hip?',
    'OSQ220': 'Over or under 50 years old?',
    'SMQ020': 'Smoked at least 100 cigarettes in life',
    'SMD030': 'Age started smoking cigarettes regularly',
    'SMQ040': 'Do you now smoke cigarettes?',
    'SMQ050Q': 'How long since quit smoking cigarettes',
    'SMQ050U': 'Unit of measure (day/week/month/year)',
    'SMD057': '# cigarettes smoked per day when quit',
    'SMQ078': 'How soon after waking do you smoke',
    'SMD641': '# days smoked cigs during past 30 days',
    'SMD650': 'Avg # cigarettes/day during past 30 days',
    'SMD093': 'May I please see the pack of cigarettes',
    'SMDUPCA': 'Cig 12-digit Universal Product Code-UPC',
    'SMD100BR': 'Cigarette Brand/sub-brand',
    'SMD100FL': 'Cigarette Filter type',
    'SMD100MN': 'Cigarette Menthol indicator',
    'SMD100LN': 'Cigarette Length',
    'SMD100TR': 'FTC Tar Content',
    'SMD100NI': 'FTC Nicotine Content',
    'SMD100CO': 'FTC Carbon Monoxide Content',
    'SMQ621': 'Cigarettes smoked in entire life',
    'SMD630': 'Age first smoked whole cigarette',
    'SMQ661': 'Brand of cigarettes smoked past 30 days',
    'SMQ665A': 'Marlboro variety',
    'SMQ665B': 'Camel variety',
    'SMQ665C': 'Newport variety',
    'SMQ665D': 'Other brand',
    'SMQ670': 'Tried to quit smoking',
    'SMQ848': '# times stopped smoking cigarettes',
    'SMQ852Q': 'How long were you able to stop smoking',
    'SMQ852U': 'Unit of measure (day/week/month/year)',
    'SMQ890': 'Ever smoked a cigar even 1 time?',
    'SMQ895': 'How many days smoked a cigar?',
    'SMQ900': 'Ever used an e-cigarette?',
    'SMQ905': 'How many days used an e-cigarette?',
    'SMQ910': 'Ever used smokeless tobacco?',
    'SMQ915': 'How many days used smokeless tobacco?',
    'SMAQUEX2': 'Questionnaire Mode Flag',
}

# directory structure
ROOT_DIR = Path(__file__).resolve().parent.parent
RAW_CSV_DIR = ROOT_DIR / "data" / "raw_csv"
RAW_XPT_DIR = ROOT_DIR / "data" / "raw_xpt"
CLEAN_DIR = ROOT_DIR / "data" / "clean_data"
CLEAN_DIR.mkdir(parents=True, exist_ok=True)

TRAIN_CSV = CLEAN_DIR / "train.csv"
VAL_CSV   = CLEAN_DIR / "val.csv"
TEST_CSV  = CLEAN_DIR / "test.csv"